### ISSUE TITLE
How to replace XsuaaMockWebServer with java-security-test?

### ISSUE THREAD

**Issue by marekviskup** [SAP/cloud-security-services-integration-library#1197]
Dear colleagues,

In a project that uses v2, we had the following EnvironmentPostProcessor.

```java
public class XsuaaMockPostProcessor implements EnvironmentPostProcessor, DisposableBean {

	private final XsuaaMockWebServer mockAuthorizationServer = new XsuaaMockWebServer();

	@Override
	public void postProcessEnvironment(ConfigurableEnvironment environment, SpringApplication application) {
		if (environment.acceptsProfiles(Profiles.of("test"))) {
			environment.getPropertySources().addFirst(this.mockAuthorizationServer);
		}
	}

	@Override
	public void destroy() throws Exception {
		this.mockAuthorizationServer.destroy();
	}
}
```

Could you kindly suggest how to replace this now that the XsuaaMockWebServer has been removed?

Thank you.

Kind regards,
Marek

**Comment by finkmanAtSap** [comment]
Hi Marek,

We suggest to use [java-security-test](https://github.com/SAP/cloud-security-services-integration-library/tree/main/java-security-test) instead as described here:
https://github.com/SAP/cloud-security-services-integration-library/blob/main/CHANGELOG.md#removed-modules

In the README, you will find links to sample code to integrate it in JUnit.
I hope that is what you are looking for.

Best,
Manuel

**Comment by Venkatsaikondeti** [comment]
Hi FinkMan
, I was just refering about the issue and I am using the same code in my project 
. I have checked the documentation you have provided, I could not find the exact replacemrnt for XSUAA mock webserver . can you please help me with what is the exact replacement for XSUAA mock webserver as it has been deprecated and it would be helpful if you can provide some documentation for the same. 

Regards,
Venkat
