### ISSUE TITLE
Is it possible to login with IAS token and use XSUAA Role Collection?

### ISSUE THREAD

**Issue by sayortanaka** [SAP/cloud-security-services-integration-library#1217]
Please tell me about the following sample;
https://github.com/SAP/cloud-security-services-integration-library/tree/main/samples/spring-security-hybrid-usage

Is it possible to login with IAS token and use XSUAA Role Collection?
not to create a Groups "Read" in IAS and assign it to your user, only to assign Xsuaa Role Collection to user, and login with IAS token.

**Comment by liga-oz** [comment]
You're talking about 2 different worlds here, if you assign role collections to user in Xsuaa it has 0 effect on IAS token. If you want to use only IAS you might consider using it together with AMS for authorization part.

**Comment by sayortanaka** [comment]
@liga-oz 

Thank you for your reply.

1. If I log in to the application on cloud foundry with a user registered with IAS, it will be automatically added to the user of SAP BTP Cockpit, but does that mean that authentication is not linked?
2. Cloud you please tell me what AMS is, link etc.?

**Comment by liga-oz** [comment]
> Is it possible for a user registered in IAS to use Role Collection?

Yes you can add RoleCollections to IAS users.

>it will be automatically added to the user of SAP BTP Cockpit, but does that mean that authentication is not linked?

Not sure what you mean by user of BTP cockpit and linked authentication

>Cloud you please tell me what AMS is, link etc.?

AMS is authorization management service it's relatively new service and is integrated in IAS, there are no external documentation I could share publicly with you at the moment.

**Comment by sayortanaka** [comment]
> Yes you can add RoleCollections to IAS users.
> Not sure what you mean by user of BTP cockpit and linked authentication

Is it possible to get the RoleCollections from the user logged into the application on cloud foundry with IAS user and password?

**Comment by sayortanaka** [comment]
> Not sure what you mean by user of BTP cockpit and linked authentication

Is it possible to get the RoleCollections from the user logged into the application on cloud foundry with IAS user and password?

What kind of cases do you anticipate when using hybrid instead of only IAS or only XSUAA?

**Comment by sayortanaka** [comment]
> Not sure what you mean by user of BTP cockpit and linked authentication

It seems to be possible with the setting of IAS, so I will try it.
Thank you for your repley.
