### ISSUE TITLE
Migrate from spring-security-jwt to nimbus-jose-jwt

### ISSUE THREAD

**Issue by Kiemes** [SAP/cloud-security-services-integration-library#1226]
org.springframework.security:spring-security-jwt was last released on May 28, 2020.

For example `spring-xsuaa-test` still uses `spring-security-jwt`. This should be replaced by `nimbus-jose-jwt`.

Source to migration guide: https://github.com/spring-projects/spring-security/wiki/OAuth-2.0-Migration-Guide#simplified-jwt-support

And a blog post https://www.springcloud.io/post/2022-02/spring-security-new-jwt/
Hope that helps.

**Comment by liga-oz** [comment]
Thanks a lot for the pointer @Kiemes, but this library is deprecated, I don't think we will invest any time in migration, but I'll keep this issue open, maybe someone from the community picks it up and provides a PR.

**Comment by finkmanAtSap** [comment]
Closing this as Github Issue section is no longer maintained.
