### ISSUE TITLE
Unable to start async servlet due to some classes from com.sap.xs.security not supporting async

### ISSUE THREAD

**Issue by boudhayan-dev** [SAP/cloud-security-services-integration-library#1239]
**Issue Summary**

I have a web servlet (web.xml) that is enabled for async processing. However, receiving the following error on request processing -

> "Unable to start async because the following classes in the processing chain do not support async [com.sap.xs.security.TenantIdValve, com.sap.xs.security.UserInfoValve, com.sap.xs.jdbc.datasource.valve.JDBCValve]"

Full stack trace -

```
java.lang.IllegalStateException: A filter or servlet of the current chain does not support asynchronous operations.","
 org.apache.catalina.connector.Request.startAsync(Request.java:1676)","
 org.apache.catalina.connector.Request.startAsync(Request.java:1670)","
 org.apache.catalina.connector.RequestFacade.startAsync(RequestFacade.java:729)","
 com.sap.cloud.cit.cdr.rest.servlets.LlmServlet.doPost(LlmServlet.java:51)","
 javax.servlet.http.HttpServlet.service(HttpServlet.java:515)","
 javax.servlet.http.HttpServlet.service(HttpServlet.java:583)","
 org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:212)","
 org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)","
 org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)","
 org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)","
 org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)","
 com.sap.cloud.cit.cdr.rest.servlets.filters.UserInfoFilter.doFilter(UserInfoFilter.java:26)","
 org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)","
 org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)","
 org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)","
 org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)","
 org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:598)","
 com.sap.xs.security.container.XSSecurityAuthenticator.invoke(XSSecurityAuthenticator.java:60)","
 org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)","
 com.sap.xs.java.valves.ErrorReportValve.invoke(ErrorReportValve.java:69)","
 ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)","
 org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)","
 com.sap.xs.jdbc.datasource.valve.JDBCValve.invoke(JDBCValve.java:62)","
 com.sap.xs.security.TenantIdValve.invoke(TenantIdValve.java:33)","
 com.sap.xs.security.UserInfoValve.invoke(UserInfoValve.java:18)","
 com.sap.xs.statistics.tomcat.valve.RequestTracingValve.invoke(RequestTracingValve.java:43)","
 com.sap.xs.logging.catalina.RuntimeInfoValve.invoke(RuntimeInfoValve.java:42)","
 org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:768)","
 org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)","
 org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617)","
 org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)","
 org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:932)","
 org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1695)","
 org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)","
 org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)","
 org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)","
 org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)","
 java.base/java.lang.Thread.run(Thread.java:829)
```

It is a non spring project.
Following are the security libs included - 
```
		<dependency>
			<groupId>com.sap.cloud.security</groupId>
			<artifactId>java-security</artifactId>
			<version>2.13.5</version>
			<exclusions>
				<exclusion>
					<groupId>org.json</groupId>
					<artifactId>json</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
```

The servlet project runs on BTP using Java 11 (`sap_java_buildpack`) and JDK

manifest entry -
>       JBP_CONFIG_COMPONENTS: "jres: ['com.sap.xs.java.buildpack.jdk.SAPMachineJDK']"

There is no library that begins with `com.sap.xs.*` namespace, except for auditlog , which is configured in the following file -

context.xml -

```
<?xml version='1.0' encoding='utf-8'?>
<Context>
    <Resource name="audit" auth="Container"
              type="com.sap.xs.audit.api.v2.AuditLogMessageFactory"
              factory="com.sap.xs.XSObjectFactory" singleton="true" />
</Context>
```

**Comment by boudhayan-dev** [comment]
I have removed the Auditlog resource as well. Still getting the error.
Not sure where are these packages being added from.

**Comment by DimitarVoynov** [comment]
Hi @boudhayan-dev, 

having in mind the NGPBUG opened for the same issue in the SAP Java Buildpack component - I would propose that you close the issue here. I don't see how the "cloud-security-services-integration-library" team can add/contribute to addressing the issue. 

Best regards, 
Dimitar

**Comment by boudhayan-dev** [comment]
Hi @DimitarVoynov ,

> having in mind the NGPBUG opened for the same issue in the SAP Java Buildpack component - I would propose that you close the issue here. 

You are right. I will close this issue here.

> I don't see how the "cloud-security-services-integration-library" team can add/contribute to addressing the issue.

The classes responsible for my issue belonged to the package - `com.sap.xs.*` , which if I am not wrong is part of the java-security libraries (or at least used to be). Hence, the first channel to reach out for resolution was this. It was only much later (after a lot of debugging), that I realised it is arising out of buildpack config.  

Hope my pov makes sense to you.
Apologies for any inconvenience.

Regards,
Dev

**Comment by liga-oz** [comment]
@boudhayan-dev just for clarification `com.sap.xs.*` namespace does not belong to the `java-security` nor any other library in this repository and has never been part of it. This library uses `com.sap.cloud.*` namespace. 

@DimitarVoynov thanks for helping out here 👍🏻

**Comment by boudhayan-dev** [comment]
@liga-oz - In that case, a misunderstanding perhaps. 
Lack of information about the valves (TenantId, UserId ..) + similar named package (security) +  references about the same package in your project led me to believe this would be the place to raise the issue.
Ref -  [Link1](https://github.com/SAP/cloud-security-services-integration-library/blob/main/java-security/README.md) [Link 2](https://github.com/SAP/cloud-security-services-integration-library/issues/360)
