### ISSUE TITLE
Revisit JWKS Cache logic

### ISSUE THREAD

**Issue by liga-oz** [SAP/cloud-security-services-integration-library#1241]
Potential suggestion:
`keySet == null || !keySet.containsAppTid(appTid) **_|| keySet.getAll().isEmpty()_**`
This will refresh empty JWKS instead of logging the error in line 175 for the whole cache duration and returning null. It means more load on XSUAA though when it returns empty JWKS.

_Originally posted by @finkmanAtSap in https://github.com/SAP/cloud-security-services-integration-library/pull/1238#discussion_r1270350843_

https://github.com/SAP/cloud-security-services-integration-library/pull/1237/files#r1269076951

**Comment by finkmanAtSap** [comment]
Closing this as Github Issue section is no longer maintained.
