### ISSUE TITLE
Jetty Server setup for local run with Spring Boot application

### ISSUE THREAD

**Issue by sourabhsparkala** [SAP/cloud-security-services-integration-library#1246]
Hello All,

I am trying to find suitable examples of templates I can use to set up 2 things with Spring Boot application. I migrated to Spring Boot 3.0 recently, but somehow all my XSUAA configurations stopped functioning.

What I need are some samples for snippets of code that could guide me in setting up the XSUAA setup
- For my local run of Spring Boot application, maybe with that Jetty Server
- For my Junit test runs using MockMvc again with the Jetty Server approach

Thank you for your insights and help.

Bets Regards
Sourabh

**Comment by finkmanAtSap** [comment]
Hi Sourabh,

Which module of this library are you using? spring-security or spring-xsuaa?

Did you take a look at the samples mentioned in the [documentation of spring-security](https://github.com/SAP/cloud-security-services-integration-library/tree/main/spring-security#samples)? The Hybrid sample is using IAS by default but it can easily be adjusted for XSUAA by passing the bean from line 39 here instead of a custom Converter: https://github.com/SAP/cloud-security-services-integration-library/blob/main/samples/spring-security-hybrid-usage/src/main/java/sample/spring/security/SecurityConfiguration.java#L54.
Please note that this bean can only be autowired if a valid XSUAA service binding is found.

It also contains an example for MockMvc:
https://github.com/SAP/cloud-security-services-integration-library/blob/8a8903a504c25e163684673567beff5f3270a367/samples/spring-security-hybrid-usage/src/test/java/sample/spring/security/junitjupiter/TestControllerIasTest.java#L17
It is based on IAS but the [java-security-test](https://github.com/SAP/cloud-security-services-integration-library/tree/main/java-security-test) module also supports mocking XSUAA tokens.

**Comment by sourabhsparkala** [comment]
@finkmanAtSap I have 3 use cases actually divided into 3 profiles

I am trying to migrate from earlier use of Spring-xsuaa to below
```
    <dependency>
      <groupId>com.sap.cloud.security</groupId>
      <artifactId>resourceserver-security-spring-boot-starter</artifactId>
      <version>3.1.0</version>
    </dependency>
```

- cloud -> Spring Boot application deployed to BTP, and there it is bounded to BTP XSUAA service
- local -> Spring Boot application used for development and Testing, but I face this issue when trying to call an endpoint
```
2023-07-28 16:38:07,201 ERROR [http-nio-8082-exec-2] - [org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]] [] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://localhost:8081/v2/foss/identifiers/types/npm": Connect to http://localhost:8081 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused] with root cause
org.apache.hc.client5.http.HttpHostConnectException: Connect to http://localhost:8081 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:549)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
        at java.base/java.net.Socket.connect(Socket.java:633)
        at org.apache.hc.client5.http.socket.PlainConnectionSocketFactory$1.run(PlainConnectionSocketFactory.java:87)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at org.apache.hc.client5.http.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:84)
        at org.apache.hc.client5.http.impl.io.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:148)
        at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:396)
        at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:158)
        at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.connectEndpoint(InternalExecRuntime.java:168)
        at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:136)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:190)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:96)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:133)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:115)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170)
        at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:75)
        at org.apache.hc.client5.http.impl.classic.CloseableHt
```
- test -> To use mockMvc yes, earlier I used to use this XSUAAConfigurationMock class which would setup a mock UAA server, but it does not seem to be so easy with the new java-security-test.


Requesting your help here.

**Comment by finkmanAtSap** [comment]
Hi Sourabh,

We are not working in support, so I can only help you with conrete questions that are explicitly related to problems with this library. We cannot support users with questions that are essentially "I can't get it to work.", sorry.

I don't see any mention of our library in the log you have posted. Also, you have given 0 information from where and how this is request was done.

Regarding java-security-test: It has a complete README that describes to use it. If there is something unclear or wrong in the documentation, please ask an explicit question, so we can answer that.

Best,
Manuel

**Comment by sourabhsparkala** [comment]
@finkmanAtSap 

I am almost there, with the Migration, but I face this issue

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springSecurityFilterChain' defined in class path resource [org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.servlet.Filter]: Factory method 'springSecurityFilterChain' threw exception; nested exception is java.lang.IllegalArgumentException: XsuaaJkuValidator requires uaaDomain.
org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)
org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:486)
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)"
```

However, I can see the `uaaDomain` in the XSUAA config from BTP

```
{
    "clientid": "",
    "clientsecret": "",
    "url": "https://fosstars-staging.authentication.eu10.hana.ondemand.com",
    "identityzone": "fosstars-staging",
    "identityzoneid": "",
    "tenantid": "",
    "tenantmode": "dedicated",
    "sburl": "https://internal-xsuaa.authentication.eu10.hana.ondemand.com",
    "apiurl": "https://api.authentication.eu10.hana.ondemand.com",
    "verificationkey": "",
    "xsappname": "",
    "subaccountid": "",
    "uaadomain": "authentication.eu10.hana.ondemand.com",
    "zoneid": "",
    "credential-type": "binding-secret"
}
```

I am allowing the Spring to Inject the `XsuaaServiceConfiguration` bean, but not sure why this property is being missed. Any suggestions?

**Comment by finkmanAtSap** [comment]
Hey, glad to hear you are making progress.

I can see that this exception occurs here: https://github.com/SAP/cloud-security-xsuaa-integration/blob/d44b0b3cb427cc159ca9567849c30e6771af9f8d/java-security/src/main/java/com/sap/cloud/security/token/validation/validators/XsuaaJkuValidator.java#L38

This means, null or a whitespace-only String was passed to constructor, most likely from here, unless you manually created a XsuaaJkuValidator object: https://github.com/SAP/cloud-security-xsuaa-integration/blob/d44b0b3cb427cc159ca9567849c30e6771af9f8d/java-security/src/main/java/com/sap/cloud/security/token/validation/validators/JwtValidatorBuilder.java#L220

This means your configuration was not correctly read by the application. Do you get the error from a deployed application or when starting the application locally? If you start locally, how are you supplying the configuration?

**Comment by finkmanAtSap** [comment]
Also, there are a lot of empty strings in the configuration, e.g. for clientid that are expected to have a value.
But I assume you removed them before posting the configuration, to keep them secret, right?

**Comment by sourabhsparkala** [comment]
> Hey, glad to hear you are making progress.
> 
> I can see that this exception occurs here: https://github.com/SAP/cloud-security-xsuaa-integration/blob/d44b0b3cb427cc159ca9567849c30e6771af9f8d/java-security/src/main/java/com/sap/cloud/security/token/validation/validators/XsuaaJkuValidator.java#L38
> 
> This means, null or a whitespace-only String was passed to constructor, most likely from here, unless you manually created a XsuaaJkuValidator object: https://github.com/SAP/cloud-security-xsuaa-integration/blob/d44b0b3cb427cc159ca9567849c30e6771af9f8d/java-security/src/main/java/com/sap/cloud/security/token/validation/validators/JwtValidatorBuilder.java#L220
> 
> This means your configuration was not correctly read by the application. Do you get the error from a deployed application or when starting the application locally? If you start locally, how are you supplying the configuration?

The error occurs when I deploy application to CF in BTP. 

Local run is working fine now. 

However, could this be the culprit
```
JwtDecoder decoder = new JwtDecoderBuilder().withXsuaaServiceConfiguration(secureApiAdapter.xsuaaServiceConfiguration)
        .build();
    
    http.sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS)
        .and()
          .oauth2ResourceServer()
            .jwt()
              .decoder(decoder)
              .jwtAuthenticationConverter(secureApiAdapter.getJwtAuthoritiesConverter());
```

That `JwtDecoderBuilder` is not configured to properly decode the XSUAA config? Requestung your inputs.

**Comment by finkmanAtSap** [comment]
Yes, absolutely! If secureApiAdapter.xsuaaServiceConfiguration does not contain a proper uaadomain, then you will get 
`IllegalArgumentException: XsuaaJkuValidator requires uaaDomain.` further down the stack.

I would look into secureApiAdapter.xsuaaServiceConfiguration next to make sure it has a proper configuration.

**Comment by sourabhsparkala** [comment]
@finkmanAtSap 

I figured out that we needed this https://github.com/SAP/cloud-security-services-integration-library/blob/main/samples/spring-security-hybrid-usage/src/main/java/sample/spring/security/SecurityConfiguration.java#L35C1-L35C118

However, I am not sure what could be happening here

```
java.lang.NoSuchMethodError: 'java.lang.String com.sap.cloud.security.xsuaa.client.OAuth2TokenKeyService.retrieveTokenKeys(java.net.URI, java.lang.String, java.lang.String)'
com.sap.cloud.security.token.validation.validators.OAuth2TokenKeyServiceWithCache.retrieveTokenKeysAndUpdateCache(OAuth2TokenKeyServiceWithCache.java:275)
com.sap.cloud.security.token.validation.validators.OAuth2TokenKeyServiceWithCache.getPublicKey(OAuth2TokenKeyServiceWithCache.java:223)
com.sap.cloud.security.token.validation.validators.JwtSignatureValidator$Validation.setPublicKey(JwtSignatureValidator.java:225)
tat com.sap.cloud.security.token.validation.validators.JwtSignatureValidator$Validation.validate(JwtSignatureValidator.java:187)
com.sap.cloud.security.token.validation.validators.JwtSignatureValidator.validate(JwtSignatureValidator.java:162)
com.sap.cloud.security.token.validation.validators.JwtSignatureValidator.validate(JwtSignatureValidator.java:94)
com.sap.cloud.security.token.validation.validators.JwtSignatureValidator.validate(JwtSignatureValidator.java:43)
com.sap.cloud.security.token.validation.CombiningValidator.validate(CombiningValidator.java:40)
com.sap.cloud.security.spring.token.authentication.HybridJwtDecoder.decode(HybridJwtDecoder.java:70)
org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationProvider.getJwt(JwtAuthenticationProvider.java:97)
org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationProvider.authenticate(JwtAuthenticationProvider.java:88)
org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:182)
org.springframework.security.oauth2.server.resource.web.BearerTokenAuthenticationFilter.doFilterInternal(BearerTokenAuthenticationFilter.java:134)
org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103)
org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89)
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:117)
org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
```

**Comment by sourabhsparkala** [comment]
> @finkmanAtSap
> 
> I figured out that we needed this https://github.com/SAP/cloud-security-services-integration-library/blob/main/samples/spring-security-hybrid-usage/src/main/java/sample/spring/security/SecurityConfiguration.java#L35C1-L35C118
> 
> However, I am not sure what could be happening here
> 
> ```
> java.lang.NoSuchMethodError: 'java.lang.String com.sap.cloud.security.xsuaa.client.OAuth2TokenKeyService.retrieveTokenKeys(java.net.URI, java.lang.String, java.lang.String)'
> com.sap.cloud.security.token.validation.validators.OAuth2TokenKeyServiceWithCache.retrieveTokenKeysAndUpdateCache(OAuth2TokenKeyServiceWithCache.java:275)
> com.sap.cloud.security.token.validation.validators.OAuth2TokenKeyServiceWithCache.getPublicKey(OAuth2TokenKeyServiceWithCache.java:223)
> com.sap.cloud.security.token.validation.validators.JwtSignatureValidator$Validation.setPublicKey(JwtSignatureValidator.java:225)
> tat com.sap.cloud.security.token.validation.validators.JwtSignatureValidator$Validation.validate(JwtSignatureValidator.java:187)
> com.sap.cloud.security.token.validation.validators.JwtSignatureValidator.validate(JwtSignatureValidator.java:162)
> com.sap.cloud.security.token.validation.validators.JwtSignatureValidator.validate(JwtSignatureValidator.java:94)
> com.sap.cloud.security.token.validation.validators.JwtSignatureValidator.validate(JwtSignatureValidator.java:43)
> com.sap.cloud.security.token.validation.CombiningValidator.validate(CombiningValidator.java:40)
> com.sap.cloud.security.spring.token.authentication.HybridJwtDecoder.decode(HybridJwtDecoder.java:70)
> org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationProvider.getJwt(JwtAuthenticationProvider.java:97)
> org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationProvider.authenticate(JwtAuthenticationProvider.java:88)
> org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:182)
> org.springframework.security.oauth2.server.resource.web.BearerTokenAuthenticationFilter.doFilterInternal(BearerTokenAuthenticationFilter.java:134)
> org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
> org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
> org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103)
> org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89)
> org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
> org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:117)
> org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
> org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
> org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
> org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
> org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
> ```

This was resolved
