### ISSUE TITLE
Issue in creating XsuaaOAuth2TokenService [implementation of TokenService] due to incompatible interfaces.

### ISSUE THREAD

**Issue by ArijitS007** [SAP/cloud-security-services-integration-library#1250]
**Problem Description:**
Issue in creating XsuaaOAuth2TokenService [implementation of TokenService] due to incompatible interfaces.

**Usecase**
We want to create **_XsuaaOAuth2TokenService_** which then be used to create XSUAATokenFlows to fetch tokens.

Refer the code snippet below:

```
HttpComponentsClientHttpRequestFactory requestFactory = new HttpComponentsClientHttpRequestFactory();
		requestFactory.setHttpClient(HttpClientFactory.create(config.getClientIdentity()));
		RestOperations restOperations = new RestTemplate(requestFactory);
		return new XsuaaOAuth2TokenService(restOperations, TokenCacheConfiguration.cacheDisabled());
```

**Issue:**
requestFactory.setHttpClient(HttpClientFactory.create(config.getClientIdentity()));
setHttpClient is used to set the HttpClient
HttpClient created by HttpClientFactory.create(cloudIdentity) and returns **_CloseableHttpClient_** from old **_org.apache.http.impl.client library [httpClient v4.5.14]_**
This is not compatibile with latest SpringBoot [HttpComponentsClientHttpRequestFactory] HttpClient.

**Already on the latest library of token-client:**
HttpClientFactory comes from [token-client v3.0.1] which is the latest .
[Inherited through latest phosphor v3.1.2-sap-02, sap-cloud-security bom]
```
<dependency>
<groupId>com.sap.cloud.security</groupId>
<artifactId>java-bom</artifactId>
<version>${version.xsuaa-java-sbom}</version>
<type>pom</type>
<scope>import</scope>
</dependency>
```

**Proposed Solution:**
The CloseableHttpClient under HttpClientFactory should now come from 
org.apache.hc.client5.http.impl.classic  [httpClient5 v5.2.x] instead of the old old org.apache.http.impl.client library 
[httpClient v4.5.14] . Along with that all compatible classes .
This is required with SpringBoot Upgrade[3.1.x] as the HttpClient/CloseableHttpClient should now be 
from org.apache.hc.client5.http.classic

**Issue Report Checklist**
- [x] Real, current bug
- [x] Not a duplicate  
- [x] Not covered in "Common Pitfalls" section of corresponding module's README.md e.g. [java-security#common-pitfalls](https://github.com/SAP/cloud-security-services-integration-library/tree/main/java-security#common-pitfalls)
- [x] Reproducible
- [x] Good summary
- [x] Well-documented 
    - [N/A] log level increased to `DEBUG` debug logs provided
    - [x] POM provided
    - [N/A] dependency tree provided
    - [x] code snippet provided (when applicable)

**Comment by liga-oz** [comment]
https://github.com/SAP/cloud-security-services-integration-library/issues/1216

**Comment by ArijitS007** [comment]
HI @liga-oz 

Thanks for your quick revert. 

Like you mentioned that this was intentional to collaborate with CAP Projects which still want to keep using HttpClient4 for now, while I agree with you on non spring projects but I feel it will be a concern for Spring Boot based CAP projects and there are many such projects.
In such cases while a project needs to upgrade to higher versions of Spring Boot (3.x) going forward and it might not be able to use HttpClient4 and has to invariably move to HttpClient5. [by November 2023 when Spring Boot 2.7.x OSS support is removed].
Also with reference to the tagged comment/issue, in my case we are not creating any arbitrary spring requests[ as mentioned in my issue description ]. Only using token-client for XSUAATokenFlows alone, so I feel the ask is justified.

**Now coming to the workaround-**
IF this is not patched from the library side, we might have to try our hand with:
Service Provider Interface(SPI) config and providing the app with a custom implementation which implements the interface of choice (HttpClient) from HttpClient5 

Though this not a perfect use case as we would not have needed any customisation over what your library provided but I don't see any other option.

**Comment by liga-oz** [comment]
You can use both 4 and 5 HttpClient versions alongside as they have different FQN, is there a specific reason why you want to use it with `HttpComponentsClientHttpRequestFactory`?

**Comment by ArijitS007** [comment]
```
HttpComponentsClientHttpRequestFactory requestFactory = new HttpComponentsClientHttpRequestFactory();
		requestFactory.setHttpClient(HttpClientFactory.create(config.getClientIdentity()));
		RestOperations restOperations = new RestTemplate(requestFactory);
		return new XsuaaOAuth2TokenService(restOperations, TokenCacheConfiguration.cacheDisabled()); 
```
with reference to the code above , i have a dependency on **_HttpComponentsClientHttpRequestFactory_**
XsuaaOAuth2TokenService implementation of OAuth2TokenService needs RestOperations which is required to create the only non-deprecated implementation of RestOperations(RestTemplate)
And to instantiate RestTemplate the most appropriate overloaded constructor for me would be RestTemplate(requestFactory)


SPI is also not an option as we cannot override the createClient method from HTTPClientFactory which has incompatible CloseableHttpClient.
**Can we use DefaultOAuth2TokenService  implementation instead of the XsuaaOAuth2TokenService , if so we can skip HttpComponentsClientHttpRequestFactory.**

**Comment by ArijitS007** [comment]
@liga-oz ,HI
 If you confirm on my last proposal : Using **_DefaultOAuth2TokenService_** instead of XsuaaOAuth2TokenService for creating tokenflows then we are good  for now. I couldn't see any major difference between the two code wise.

IF so we can close this issue/thread.

**Comment by ArijitS007** [comment]
Thank you . I am closing the issue.
