### ISSUE TITLE
JwtDecoder not configured by XSUAA lib for X.509 bindings with httpclient 4

### ISSUE THREAD

**Issue by Sheetal-B-Mohite** [SAP/cloud-security-services-integration-library#1262]
**Issue Summary**
After upgrading to Springboot 3, CAP Java 2.1, JDK 17 our application failed to start at runtime with the following message:
`Parameter 0 of method setFilterChains in org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration required a bean of type 'org.springframework.security.oauth2.jwt.JwtDecoder' that could not be found.`

However when we create a jwtDecoder bean it seems to work. But this isn't an ideal way.
```
@Bean("JwtDecoder")
    public JwtDecoder jwtDecoder(){
        return new XsuaaJwtDecoderBuilder(xsuaaServiceConfiguration).build();
    }
```

From `com/sap/cds/framework/spring/config/auth/xsuaa/XsuaaSecurityConfig.java#87` it isn't able to get the bean and pass it to
`org/springframework/security/config/annotation/web/configurers/oauth2/server/resource/OAuth2ResourceServerConfigurer.java#437`

Also please refer to: https://github.tools.sap/cap/issues/issues/14212#issuecomment-3508705 
Could you kindly provide a fix?

**Comment by shubhijain** [comment]
Following this as I am also facing same issue.

**Comment by liga-oz** [comment]
Hi @Sheetal-B-Mohite,

[spring-xsuaa](https://github.com/SAP/cloud-security-services-integration-library/tree/main/spring-xsuaa) module is configured to use `httpclient 5` as it initializes the `RestTemplate` where the `httpclient 5` is mandatory (starting with spring-web version 6.x). If you want to use httpclient 4 then you have to switch to [spring-security](https://github.com/SAP/cloud-security-services-integration-library/tree/main/spring-security) module. 

I would also want to point out that the `spring-xsuaa` module is deprecated and you should plan to migrate to the `spring-security`, you can find migration guide [here](https://github.com/SAP/cloud-security-services-integration-library/blob/main/spring-security/Migration_SpringXsuaaProjects.md).

Nevertheless, to fix the missing bean error, you just have to add the httpclient 5 dependency in your project's pom
```xml
<dependency>
	<groupId>org.apache.httpcomponents.client5</groupId>
	<artifactId>httpclient5</artifactId>
	<version>5.x.x</version>
</dependency>
```

**Comment by kawal2266** [comment]
I'm also facing the same issue :

Even though I have added the dependency -

<dependency>
    		<groupId>org.apache.httpcomponents.client5</groupId>
    		<artifactId>httpclient5</artifactId>
    		<version>5.1</version>
</dependency>

I get -

_Description:

Parameter 0 of method setFilterChains in org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration required a bean of type 'org.springframework.security.oauth2.jwt.JwtDecoder' that could not be found.


Action:

Consider defining a bean of type 'org.springframework.security.oauth2.jwt.JwtDecoder' in your configuration._

**Comment by finkmanAtSap** [comment]
There are already JwtDecoder beans provided by the library but they are conditional. They are only created if necessary. For example, the XsuaaJwtDecoder is only created when the application is bound to an XSUAA instance:

https://github.com/SAP/cloud-security-services-integration-library/blob/b5142afe100a993133b55a19009ea740f6cb6d22/spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/autoconfiguration/XsuaaResourceServerJwkAutoConfiguration.java#L48

To help you, we need more information, in particular:

- Which client library (e.g. spring-xsuaa, spring-security etc.) of this repository are you using exactly?
- Are you consuming this library via the CAP framework (first question included com.sap.cds namespace)?
- Are you using XSUAA, IAS or both at the same time?
- Does the problem occur deployed on BTP or when starting the application locally?

Please follow this guide to get a report by Spring Boot why our JwtDecoder beans (e.g. XsuaaJwtDecoder or IasJwtDecoder or HybridJwtDecoder) are NOT getting created by our lib via auto-configuration:
https://www.baeldung.com/spring-boot-auto-configuration-report
Once we know the reason, we can work from there.

Best,
Manuel

**Comment by kawal2266** [comment]
Hi ,

Thanks for the reply, I did the same as mentioned by @Sheetal-B-Mohite , while migrating :

1. **Dependency :** 

Removed the dependency:-

 ```
 <dependency>
            <groupId>com.sap.cloud.security.xsuaa</groupId>
            <artifactId>xsuaa-spring-boot-starter</artifactId>
            <version>2.11.13</version>
        </dependency>
```
Added the dependency:-

```
<dependency>
    	<groupId>com.sap.cloud.security</groupId>
    	<artifactId>resourceserver-security-spring-boot-starter</artifactId>
    	<version>3.1.3</version>
</dependency>
<dependency>
    	<groupId>org.apache.httpcomponents.client5</groupId>
    	<artifactId>httpclient5</artifactId>
    	<version>5.1</version>
</dependency>
<dependency>
         <groupId>com.sap.cloud.security.xsuaa</groupId>
         <artifactId>spring-security-compatibility</artifactId>
</dependency>

```
2. Yes, the CAP framework is used
3. XSUAA with the default identity provider
4. Getting this error when running locally 

Thanks,
Kawal

**Comment by finkmanAtSap** [comment]
Tip: You can bind your local application to a XSUAA service from BTP via [CAP Hybrid testing](https://cap.cloud.sap/docs/advanced/hybrid-testing#introduction).

After binding to your XSUAA service locally, you can start the application with active profile set to "hybrid" and the XSUAA binding should be provided to our application, so the bean should become available.

**Comment by seraphionhd** [comment]
We have exactly the same problem at the moment. Locally everything works, but when we deploy via CloudFoundry we get the same in our Logs:

`Parameter 0 of method setFilterChains in org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration required a bean of type 'org.springframework.security.oauth2.jwt.JwtDecoder' that could not be found.`

We also use this dep already:

`<dependency>
    	<groupId>org.apache.httpcomponents.client5</groupId>
    	<artifactId>httpclient5</artifactId>
    	<version>5.1</version>
</dependency>`

When adding this, everything works as expected:

`@Bean("JwtDecoder")
    public JwtDecoder jwtDecoder(){
        return new XsuaaJwtDecoderBuilder(xsuaaServiceConfiguration).build();
    }`

Any ideas? :-)

**Comment by liga-oz** [comment]
> We have exactly the same problem at the moment. Locally everything works, but when we deploy via CloudFoundry we get the same in our Logs:
> 
> `Parameter 0 of method setFilterChains in org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration required a bean of type 'org.springframework.security.oauth2.jwt.JwtDecoder' that could not be found.`
> 
> We're also using this dep already:
> 
> ```
> <dependency>
>         <groupId>org.apache.httpcomponents.client5</groupId>
>     	<artifactId>httpclient5</artifactId>
>     	<version>5.1</version>
> </dependency>
> ```
> 
> When adding this, everything works as expected:
> 
> ```java
> @Bean("JwtDecoder")
>     public JwtDecoder jwtDecoder(){
>         return new XsuaaJwtDecoderBuilder(xsuaaServiceConfiguration).build();
> }
> ```
> 
> 1. Which client library (e.g. spring-xsuaa, spring-security etc.) of this repository are you using exactly?
>    
>    * spring-xsuaa 3.1.3
>    * spring-security 3.1.3
> 2. Are you consuming this library via the CAP framework (first question included com.sap.cds namespace)?
>    
>    * Via CAP Framework
> 3. Are you using XSUAA, IAS or both at the same time?
>    
>    * XSUAA
> 4. Does the problem occur deployed on BTP or when starting the application locally?
>    
>    * when deployed on BTP
> 
> Any ideas? :-)

spring-xsuaa and spring-security shouldn't be used together, under the hood they perform identical functionality. Please use only spring-security and for the spring-security make sure that you have `IdentityServicesPropertySourceFactory` defined like here https://github.com/SAP/cloud-security-services-integration-library/blob/main/samples/spring-security-hybrid-usage/src/main/java/sample/spring/security/SecurityConfiguration.java#L35 and for spring-security httpClient 5 dependency is not required.

**Comment by finkmanAtSap** [comment]
I think @liga-oz meant XsuaaServicePropertySourceFactory since you are using XSUAA. IdentityServicesPropertySourceFactory is for IAS.

**Comment by seraphionhd** [comment]
I was able to find the issue. It seems like there where versioning mismatches within my spring dependencies. In combination with removing spring-xsuaa and only using spring-security, it seems to work now! :-)
