### ISSUE TITLE
Missing Statement in Migration Documentation about PropertySource Annotation when migrating from spring-xsuaa to SAP BTP spring-security

### ISSUE THREAD

**Issue by clnative** [SAP/cloud-security-services-integration-library#1269]
**Issue Summary**
The migration guide at https://github.com/SAP/cloud-security-services-integration-library/blob/2.14.1/spring-security/Migration_SpringXsuaaProjects.md misses the fact that the 

```java
@PropertySource(factory = IdentityServicesPropertySourceFactory.class, ignoreResourceNotFound = true, value = { "" }) // might be auto-configured in a future release
```

line must be added to the `WebSecurityConfigurerAdapter` as described in https://github.com/SAP/cloud-security-services-integration-library/tree/2ceaf87fc709cd4ce09d94823efaf886a1ffa5e5/spring-security#setup-spring-security-oauth-20-resource-server .
Without that line, the migration is incomplete and no configuration data is provided to the `XsuaaServiceConfiguration`(s).

**Issue Report Checklist**

- [x] Real, current bug
- [x] Not a duplicate  
- [x] Not covered in "Common Pitfalls" section of corresponding module's README.md e.g. [java-security#common-pitfalls](https://github.com/SAP/cloud-security-services-integration-library/tree/main/java-security#common-pitfalls)
- [x] Reproducible
- [x] Good summary, well I think so
- [x] Well-documented , all below not applicable
    - [ ] log level increased to `DEBUG` debug logs provided, not applicable
    - [ ] POM provided, not applicable
    - [ ] dependency tree provided, not applicable
    - [ ] code snippet provided (when applicable), not applicable

**Comment by liga-oz** [comment]
Closing as the migration documentation has been updated.
