### ISSUE TITLE
java.lang.NoSuchMethodError: com.sap.cloud.security.xsuaa.tokenflows.XsuaaTokenFlows.userTokenFlow()

### ISSUE THREAD

**Issue by dayakarmandalapu** [SAP/cloud-security-services-integration-library#1282]
I am upgrading springboot from 2.7.12 to 3.1.2 for our Content Agent Service (CAS) project.
 
I am facing below error related to XSUAA Token even after using latest 3.1.3 version for cloud security libraries –
https://github.com/SAP/cloud-security-services-integration-library/releases/tag/3.0.0

https://github.wdf.sap.corp/content-agent/cas/blob/feat/SpringBoot3_upgrade/cas-core/src/main/java/com/sap/cloud/lm/sl/contentlm/cas/core/utils/TokenHandler.java#L142 –> we are using client credentials token flow and no where used userTokenFlow but still getting below error.
 
2023-08-31T16:08:35.77+0530 [APP/PROC/WEB/0] OUT 2023-08-31T10:38:35.769Z ERROR 7 --- [nio-8080-exec-2] c.s.c.l.s.c.c.e.c.CASExceptionHandler    : Handler dispatch failed: **java.lang.NoSuchMethodError: 'com.sap.cloud.security.xsuaa.tokenflows.UserTokenFlow com.sap.cloud.security.xsuaa.tokenflows.XsuaaTokenFlows.userTokenFlow()**'
   2023-08-31T16:08:35.77+0530 [APP/PROC/WEB/0] OUT jakarta.servlet.ServletException: Handler dispatch failed: java.lang.NoSuchMethodError: 'com.sap.cloud.security.xsuaa.tokenflows.UserTokenFlow com.sap.cloud.security.xsuaa.tokenflows.XsuaaTokenFlows.userTokenFlow()'
 
Link for Code repository - https://github.wdf.sap.corp/content-agent/cas/blob/feat/SpringBoot3_upgrade

**Comment by finkmanAtSap** [comment]
https://github.com/SAP/cloud-security-services-integration-library/blob/main/CHANGELOG.md#:~:text=UserTokenFlow%20%E2%86%92%20use%20instead%20JwtBearerTokenFlow

**Comment by finkmanAtSap** [comment]
Hi,

I am sorry but I don't know how I can help. Our 3.x codebase does not have calls to this method anywhere. It is only mentioned in CHANGELOG and in a comment.

You might have some other dependency calling the method that is expecting our lib to be present in version 2.x. Are you perhaps using Java Buildpack or Cloud SDK?

**Comment by dayakarmandalapu** [comment]
Hi,

I am using Java Buildpack.

properties:
      JBP_CONFIG_SAP_MACHINE_JRE: '{ jre: { version: 17.+ } }'
      JBP_CONFIG_COMPONENTS: '{ jres: ["JavaBuildpack::Jre::SapMachineJRE"] }'
parameters:
      buildpack: java_buildpack
      backend-url: ${default-url}

**Comment by finkmanAtSap** [comment]
I checked with colleagues from SAP Java Buildpack and we do not think it is related to this.

Can you please provide a more detailed stack trace, so we can see the location that calls 

com.sap.cloud.security.xsuaa.tokenflows.XsuaaTokenFlows.userTokenFlow()?

**Comment by dayakarmandalapu** [comment]
Hi, 
I fixed the issue. We were using older versions (v 2.2.2) of - Audit log related libraries in our project (audit-java-client-api, audit-java-client-impl) which were depending on  XsuaaTokenFlows.userTokenFlow(). After upgrading to latest version 2.6.4, issue got resolved.

https://github.wdf.sap.corp/audit-log-service/cf-audit-java-client/wiki/Audit-Log-V2

Thanks you!

**Comment by finkmanAtSap** [comment]
I'm happy to hear that. Thank you for sharing your solution!
