### ISSUE TITLE
resourceserver-security-spring-boot-starter should include spring-boot-starter-security

### ISSUE THREAD

**Issue by StefanHenke** [SAP/cloud-security-services-integration-library#1296]
**Is your feature request related to a problem? Please describe.**
When migrating from `spring-xsuaa` to `resourceserver-security-spring-boot` it is not obvious that my application needs a new direct dependency to spring-boot-starter-security. Though it is documented, it is easy to be missed by developers because both libraries behave differently.

**Describe the solution you'd like**
**Issue Summary**
According to the documentation of `resourceserver-security-spring-boot-starter` library, applications have to define two dependencies:
```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-security</artifactId>
</dependency>
<dependency>
    <groupId>com.sap.cloud.security</groupId>
    <artifactId>resourceserver-security-spring-boot-starter</artifactId>
    <version>3.1.3</version>
</dependency>
```

In contrast to `spring-xsuaa` starter bundle, applications additionally have to have a direct dependency to spring-boot-starter-security. Why isn´t this done the same way to the starter module of `resourceserver-security-spring-boot-starter`? It would feel more natural this way and avoid issues by stakeholders which miss this dependency.

Best regards,
Stefan

**Comment by liga-oz** [comment]
Hi @StefanHenke,

There are few reasons why it hasn't been included as it was with the `xsuaa-spring-boot-starter`:

1. Flexibility: By not including the `spring-boot-starter-security` dependency in the `resourceserver-security-spring-boot-starter` POM,  the end users have more control over the version of the spring-boot security library they want to use. They can choose to use a different version , depending on their specific requirements.

2. Reduced Transitive Dependencies: Including the `spring-boot-starter-security` dependency in the `resourceserver-security-spring-boot-starter` POM would introduce all the transitive dependencies of the spring-boot-security library to every project that uses the starter. This can result in a larger and potentially bloated dependency tree. By defining the spring boot security dependency directly(or using only transitive dependencies from it that are required in a project), the end users reduce the number of unnecessary transitive dependencies.

3. Avoiding Conflicts: Including the `spring-boot-starter-security` dependency in the `resourceserver-security-spring-boot-starter` POM could potentially lead to conflicts with other dependencies that the end users might have in their projects. By allowing the end users to define the security dependency directly, they can manage any conflicts or compatibility issues that might arise.

**Comment by finkmanAtSap** [comment]
Closing this as Github Issue section is no longer maintained.
