### ISSUE TITLE
HybridTokenFactory does not use Spring configured Xsuaa/Token configuration

### ISSUE THREAD

**Issue by patrickhuy** [SAP/cloud-security-services-integration-library#1301]
**Issue Summary**
HybridTokenFactory reads the `xsAppId` by calling `Environments.getCurrent().getXsuaaConfiguration();` 
https://github.com/SAP/cloud-security-services-integration-library/blob/9954138/java-security/src/main/java/com/sap/cloud/security/servlet/HybridTokenFactory.java#L82

This will then use various strategies to attempt to read an `OAuth2ServiceConfiguration` but does not attempt to read the properties in the spring application context. This leads to HybridTokenFactory using a different (or no) OAuth2ServiceConfiguration than the one used in com.sap.cloud.security.spring.autoconfig.HybridAuthorizationAutoConfiguration#xsuaaAuthConverter (which uses an `XsuaaServiceConfiguration` which is read via Spring mechanisms)

When that happens a message is logged each request
```
HybridTokenFactory             : There is no xsuaa service configuration: no local scope check possible.```
```

However within `XsuaaTokenAuthorizationConverter` the xsuaa configuration from the Spring context is used which makes that one work as expected.

*** Expected Result ***
Service configuration for XSUAA or IAS should be used from the Spring context consistently to enable consistent behaviour across environments.
Potentially `HybridIdentityServicesAutoConfiguration` should/could configure `HybridTokenFactory`, potentially via `HybridJwtDecoder` - that one currently uses the static method `Token.create(encodedToken)` to create a token.

**Issue Report Checklist**

- [x] Real, current bug
- [x] Not a duplicate  
- [x] Not covered in "Common Pitfalls" section of corresponding module's README.md e.g. [java-security#common-pitfalls](https://github.com/SAP/cloud-security-services-integration-library/tree/main/java-security#common-pitfalls)
- [x] Reproducible
- [ ] Good summary
- [x] Well-documented 
    - [ ] log level increased to `DEBUG` debug logs provided
    - [ ] POM provided
    - [ ] dependency tree provided
    - [ ] code snippet provided (when applicable)

**Comment by finkmanAtSap** [comment]
Closing this as Github Issue section is no longer maintained.
