### ISSUE TITLE
Spring applications miss the certificate in SecurityContext

### ISSUE THREAD

**Issue by mwdb** [SAP/cloud-security-services-integration-library#1332]
Please first read carefully [Report an issue](https://github.com/SAP/cloud-security-services-integration-library/blob/main/CONTRIBUTING.md#report-an-issue) section before creating an Issue.

**Issue Summary**
- A clear and concise description of the issue.
mTLS certificates are only available when validating certificates via servlet filters. In this case they are set via https://github.com/SAP/cloud-security-services-integration-library/blob/main/java-security/src/main/java/com/sap/cloud/security/servlet/IasTokenAuthenticator.java#L30 (same for xsuaaTokenAuthenticator).

When using spring security, servlet filter chains are not invoked and instead you'd need to add something like

```
   public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
        // @formatter:off
        http.addFilterBefore(
                new X509ExtractionFilter(), WebAsyncManagerIntegrationFilter.class);
...
```
and
`public class X509ExtractionFilter extends GenericFilterBean {

    private static final Logger logger = LoggerFactory.getLogger(X509ExtractionFilter.class);

    @Override
    public void doFilter(
            ServletRequest request,
            ServletResponse response,
            FilterChain chain) throws IOException, ServletException {
        if (request instanceof HttpServletRequest) {
            String certificateHeader = getClientCertificate((HttpServletRequest) request);
            if (certificateHeader != null) {
                try {
                    SecurityContext.setClientCertificate(X509Certificate.newCertificate(certificateHeader));
                } catch (Exception e) {
                    logger.info("Error parsing certificate", e);
                }
            }else {
                SecurityContext.clear();
            }
        }
        chain.doFilter(request, response);

    }
`

- Steps to reproduce the problem: 1. 2. 3.
Write a validator for Spring relying on certificates
- What is the expected result?
SecurityCOntext contains the certificate
- What happened instead?
No certificate available in the SecurityContext
- Additional information? (attach screenshots if applicable)

**Issue Report Checklist**

- [x] Real, current bug
- [x] Not a duplicate  
- [x] Not covered in "Common Pitfalls" section of corresponding module's README.md e.g. [java-security#common-pitfalls](https://github.com/SAP/cloud-security-services-integration-library/tree/main/java-security#common-pitfalls)
- [x] Reproducible
- [x] Good summary
- [x] Well-documented 
    - [ ] log level increased to `DEBUG` debug logs provided
    - [ ] POM provided
    - [ ] dependency tree provided
    - [ ] code snippet provided (when applicable)

**Comment by finkmanAtSap** [comment]
Closing this as Github Issue section is no longer maintained.
