### ISSUE TITLE
Spring Boot 3 Migration: Parsing issue for public key used from java-security-test while decoding JWT token

### ISSUE THREAD

**Issue by kamranidrees** [SAP/cloud-security-services-integration-library#1348]
Hi Colleagues,

In our WebSecuirtyConfig file, we have OAuth2 secuirty filter chain with custom Jwt decoder as shown below:

        public JwtDecoder getJwtDecoder() {
            XsuaaCredentials brokerXsuaaCredentials = brokerCredentials();
            XsuaaAudienceValidator customAudienceValidator = new XsuaaAudienceValidator(customXsuaaConfig());
            customAudienceValidator.configureAnotherXsuaaInstance(brokerXsuaaCredentials.getXsAppName(), brokerXsuaaCredentials.getClientId());
            return new XsuaaJwtDecoderBuilder(customXsuaaConfig()).withTokenValidators(customAudienceValidator).build();
        }

Now for the JWT token when the XsuaaJwtDecoder is invoked from spring-xsuaa-3.2.0 library, it attempts to verify the JWT token which is generated by JwtGenerator from java-security-test-3.2.0 library. The stack-trace shows that eventually the NimbusJwtDecoder is invoked which then attempts to parse the public key for verifying the token and this fails with the error "The modulus value must not be null".

at com.nimbusds.jose.jwk.JWKSet.parse(JWKSet.java:427)
Error Msg: Failed to retrieve JWK set. Invalid JWK at position 0: The modulus value must not be null

Please find attached image of stack trace.
![Screenshot 2023-11-09 at 09 38 05](https://github.com/SAP/cloud-security-services-integration-library/assets/2745892/991425eb-cacb-4728-98cd-52fd2ed38db2)

Could you please guide us that how to proceed further from here?

Thank you very much!

Best regards,
Kamran

**Comment by finkmanAtSap** [comment]
Hi Kamran,

Unfortunately we do not have the resources for consultation at the moment.
For this reason, we will update our guidelines for consultation support in the next days to move to a different place than GH issues.
Can you please try to pose your question on https://sap.stackenterprise.co/ as you seem to be an employee of SAP with access to this? Maybe someone else can you help you sooner. We will try to get to your question as soon as possible. I'm afraid I do not have an idea right off the bat what could be the issue here.

**Comment by kamranidrees** [comment]
I have fixed the issue.

**First fix:** Our **_oauth/token_keys_** endpoint was returning the public key without additional attributes which are required by RSAKey.parse(final Map<String, Object> jsonObject) used from nimbus-jose-jwt-9.31 library which is dependency for XsuaaJwtDecoder from spring-xsuaa-3.2.0 library.

Original Response from end point oauth/token_keys which led to parsing issue with the usage of spring-xsuaa with migration however had no issue in previously used spring-security-oauth2 library

```
{
    "keys": [
        {
            "kty": "RSA",
            "value": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzI7Ysxdqxc9cQU58JYxW\nBeNVMbscuzp3wFrE8BmOt+i7FbijAskHYVo6fPxOcOH5usXc3hyhJvlB69T/+LF9\nkoqdLaTg05H2riYqtslek670MyC0TsCyUdgOAX/Qoj24KaU4JgRPxoApXWg7bVZ7\nPyRq8Nz3nVUGWrtv8+jxWUYEMf7q4N2tpsGKMyMVDUOgwi0vYAPg8PiyrB4gRJSQ\nl6skvE9twbflow9ut1MjywvQEkMLIBXA7TwmUR3IVqYvRvO46WaOTEqGaEgjTrMC\nwHp5sJNsrmH88WaAjMkxh4OLGX9QdZh6rJjFQGlw+COCEEZXB0TCIKL2KyTQNtl4\nEQIDAQAB\n-----END PUBLIC KEY-----"
        }
    ]
}
```

Partially fixed Response from end point oauth/token_keys - No public key parsing issue but still signature verification failed

```
..
    {
      "kty": "RSA",
      "e": "10001",
      "use": "sig",
      "kid": "default-kid",
      "alg": "RS256",
      "value": "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAm1QaZzMjtEfHdimrHP3/2Yr+1z685eiOUlwybRVG9i8wsgOUh+PUGuQL8hgulLZWXU5MbwBLTECAEMQbcRTNVTolkq4i67EP6JesHJIFADbK1Ni0KuMcPuiyOLvDKiDEMnYG1XP3X3WCNfsCVT9YoU+lWIrZr/ZsIvQri8jczr4RkynbTBsPaAOygPUlipqDrpadMO1momNCbea/o6GPn38LxEw609ItfgDGhL6f/yVid5pFzZQWb+9l6mCuJww0hnhO6gt6Rv98OWDty9G0frWAPyEfuIW9B+mR/2vGhyU9IbbWpvFXiy9RVbbsM538TCjd5JF2dJvxy24addC4oQIDAQAB",
      "n": "9b541a673323b447c77629ab1cfdffd98afed73ebce5e88e525c326d1546f62f30b2039487e3d41ae40bf2182e94b6565d4e4c6f004b4c408010c41b7114cd553a2592ae22ebb10fe897ac1c92050036cad4d8b42ae31c3ee8b238bbc32a20c4327606d573f75f758235fb02553f58a14fa5588ad9aff66c22f42b8bc8dccebe119329db4c1b0f6803b280f5258a9a83ae969d30ed66a263426de6bfa3a18f9f7f0bc44c3ad3d22d7e00c684be9fff2562779a45cd94166fef65ea60ae270c3486784eea0b7a46ff7c3960edcbd1b47eb5803f211fb885bd07e991ff6bc687253d21b6d6a6f1578b2f5155b6ec339dfc4c28dde49176749bf1cb6e1a75d0b8a1"
    }
..
```

**Second fix:** The RSASignature.engineVerify() from java base library (sun.security.rsa) validates the length of signature which uses modulus from the public key that had different length i.e. 384 instead of expected 256. In order to fix this, I had to also encode the modulus using Base64 encoding like public key.

Final Fixed response from oauth/token_keys endpoint

```
..
    {
      "kty": "RSA",
      "e": "AQAB",
      "use": "sig",
      "kid": "default-kid",
      "alg": "RS256",
      "value": "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAm1QaZzMjtEfHdimrHP3/2Yr+1z685eiOUlwybRVG9i8wsgOUh+PUGuQL8hgulLZWXU5MbwBLTECAEMQbcRTNVTolkq4i67EP6JesHJIFADbK1Ni0KuMcPuiyOLvDKiDEMnYG1XP3X3WCNfsCVT9YoU+lWIrZr/ZsIvQri8jczr4RkynbTBsPaAOygPUlipqDrpadMO1momNCbea/o6GPn38LxEw609ItfgDGhL6f/yVid5pFzZQWb+9l6mCuJww0hnhO6gt6Rv98OWDty9G0frWAPyEfuIW9B+mR/2vGhyU9IbbWpvFXiy9RVbbsM538TCjd5JF2dJvxy24addC4oQIDAQAB",
      "n": "AJtUGmczI7RHx3Ypqxz9_9mK_tc-vOXojlJcMm0VRvYvMLIDlIfj1BrkC_IYLpS2Vl1OTG8AS0xAgBDEG3EUzVU6JZKuIuuxD-iXrBySBQA2ytTYtCrjHD7osji7wyogxDJ2BtVz9191gjX7AlU_WKFPpViK2a_2bCL0K4vI3M6-EZMp20wbD2gDsoD1JYqag66WnTDtZqJjQm3mv6Ohj59_C8RMOtPSLX4AxoS-n_8lYneaRc2UFm_vZepgricMNIZ4TuoLekb_fDlg7cvRtH61gD8hH7iFvQfpkf9rxoclPSG21qbxV4svUVW27DOd_Ewo3eSRdnSb8ctuGnXQuKE="
    }
..
```

**Comment by finkmanAtSap** [comment]
Happy to hear that, thanks for sharing your solution!
