### ISSUE TITLE
OAuth2RestTemplate deprecated from spring boot 3

### ISSUE THREAD

**Issue by VanitaDhanagar** [SAP/cloud-security-services-integration-library#1367]
**Question Summary**
If applicable, please mention:
- client library (token-client) and 3.3.0
- Environment: Cloud Foundry 
- Additional information

I want to migrate a application from spring boot 2 to 3 and we are stuck wth OAuth2RestTemplate which is no longer supported 

		<dependency>
			<groupId>org.springframework.security.oauth</groupId>
			<artifactId>spring-security-oauth2</artifactId>
			<version>2.5.0.RELEASE</version>
		</dependency>

I see custome token flow https://github.com/SAP/cloud-security-services-integration-library/tree/main/token-client#custom-xsuaatokenflows-bean   how do i do it for other services like enterprise messaging service(ems) ,more info on code https://github.com/SAP-samples/cloud-espm-cloud-native/blob/main/worker/src/main/java/com/sap/refapps/espm/config/EnterpriseMessagingConfig.java

Kinldy guide us in migrating the application 

Regards,
vanita

**Comment by liga-oz** [comment]
For migration topics related to spring framework please ask your questions in their repository https://github.com/spring-projects/spring-framework
