### ISSUE TITLE
OIDC Token Validation Issue - fetch app_tid

### ISSUE THREAD

**Issue by jeswant** [SAP/cloud-security-services-integration-library#1396]
**Question Summary**
- client library: sap.cloud.security.version:2.17.2
- Environment: Kubernetes
- Additional information

We have recently upgraded our maven package for our java application com.sap.cloud.security in pom xml from version 2.8.12 to 2.17.2 and now get the following error:

> ValidationResults: Token signature can not be validated because: OIDC token must provide the app_tid claim for tenant validation when issuer is not the same as the url from the service credentials

We currently use this method `OAuth2ServiceConfigurationBuilder` in our java application to pass the client, url and client secret and then set up our token authenticator `iasTokenAuthenticator.withServiceConfiguration(oAuth2ServiceConfiguration)`. I am wondering to get `app_tid` as part of the OIDC token, do we pass in the application id of the app in our Cloud Identity Services to one of these methods or do we change a setting of the application itself inside of Cloud Identity Services. Thanks!

```
	public IasTokenAuthenticator configTokenAuthenticator(BrokerConfig config) {
		OAuth2ServiceConfiguration oAuth2ServiceConfiguration = OAuth2ServiceConfigurationBuilder
			.forService(Service.IAS).withClientId(config.getOIDCProperties().getClientId())
			.withClientSecret(config.getOIDCProperties().getClientSecret())
			.withUrl(config.getOIDCProperties().getTokenUrl()).build();
		IasTokenAuthenticator iasTokenAuthenticator = new IasTokenAuthenticator();
		iasTokenAuthenticator.withServiceConfiguration(oAuth2ServiceConfiguration);
		return iasTokenAuthenticator;
	}

```

**Comment by liga-oz** [comment]
Hi @jeswant,

By default the IAS Signature validator requires `app_tid` claim in the OIDC token for the token validation. There are 2 options how to deal with this requirement:
1. You can disable tenant ID check https://github.com/SAP/cloud-security-services-integration-library/blob/main/java-security/src/main/java/com/sap/cloud/security/token/validation/validators/JwtValidatorBuilder.java#L194
2. Provide the `app_tid` in the OIDC token (not 100% sure if that is possible)

Kind Regards,
Liga
