### ISSUE TITLE
Unable to start application in CF with Service plan "reference-instance"

### ISSUE THREAD

**Issue by VasudhaRao** [SAP/cloud-security-services-integration-library#1435]
We have a Java application in Cloud Foundry. We are unable to start our application. This is the error which we have received in the logs. 
**org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [com.sap.gs.translationhub.proxy.ProxyApplication]; nested exception is java.lang.IllegalArgumentException: No enum constant com.sap.cloud.security.config.cf.CFConstants.Plan.REFERENCE-INSTANCE**
 
The same application works fine for Service Plan- "Broker". We have also referenced this issue "[https://github.com/SAP/cloud-security-services-integration-library/issues/1279"](https://github.com/SAP/cloud-security-services-integration-library/issues/1279%22) where getServiceConfigurationsAsList is mentioned. But we could not find the package to import.
Also, tried adding this configuration in WebSecurityConfiguration file, but could not reach this point as application failed to start.
Environments.getCurrent().getXsuaaConfiguration().getProperty(SERVICE_PLAN).equals("reference-item");

We have created the reference-instance in the following manner. We have created a service instance in Kyma and we are using reference-instance plan to use it in our CF application.

Adding the logs of our application.
 
- client library - jdk 11, sap-cloud-security - 2.17.2, security-patched-spring-boot-starter - 2.7.17-sap-01
- Environment: Cloud Foundry
 
Could you let us know, how we could configure the "reference-instance" in our application.

[sth proxy logs.txt](https://github.com/SAP/cloud-security-services-integration-library/files/13962736/sth.proxy.logs.txt)

**Comment by VasudhaRao** [comment]
Hi Manuel, 
We have raised the issue in Stack@SAP, but could not get any response to our query. https://sap.stackenterprise.co/questions/49039
![xsuaa](https://github.com/SAP/cloud-security-services-integration-library/assets/29860753/45e43ed2-4d58-46ec-9a90-ee79fedf059b)

The solution provided in the ticket works fine for non spring based application. 
We also found a similar issue raised for XSUUA service plan "apiaccess". https://github.com/SAP/cloud-security-services-integration-library/issues/382 . This issue is resolved as APIACCESS is now available in ENUM Plan.
 
The issue continues to exist even after making the changes. Could you please look into it?
Also, attaching the java-api library imported by team, with CFConstants.  
 
Thanks and Regards,
Vasudha

**Comment by finkmanAtSap** [comment]
Answered on [Stack@SAP](https://sap.stackenterprise.co/questions/49039/50175#50175)
