### ISSUE TITLE
Package name conflict

### ISSUE THREAD

**Issue by holgpar** [SAP/cloud-security-services-integration-library#1455]
Hi,

I try to use both "spring.xsuaa" and "token.client" with a project using [java  9 modules](https://www.oracle.com/corporate/features/understanding-java-9-modules.html).

I ran into the following issue:

> java: module entities reads package com.sap.cloud.security.xsuaa from both spring.xsuaa and token.client

It is because the two modules define the same package.

Do you provide modules which work with this java feature? For example be combining the classes into into one module?
Do you plan to disentangle you package structure?

Many thanks, Holger

**Comment by finkmanAtSap** [comment]
Hi Holger, at the moment, there are no plans to add module support to this lib, sorry.

Closing this as Github Issue section is no longer maintained.
