### ISSUE TITLE
Artifact not published `com.sap.cloud.security:resourceserver-security-spring-boot-starter:2.17.3`

### ISSUE THREAD

**Issue by newtork** [SAP/cloud-security-services-integration-library#1491]
Hello colleagues,

I'm from the [SAP Cloud SDK](https://sap.github.io/cloud-sdk/) team.
We need to be compatible with _SAP Java/Jakarta Buildpack_. This means we need to support the very same dependency version for the _SAP Security library_. 

Unfortunately we found the following dependency not being resolvable:
* `com.sap.cloud.security:resourceserver-security-spring-boot-starter:2.17.3`

https://github.com/SAP/cloud-security-services-integration-library/blob/fdabc30eac5fbe02f2fab8f5d28802feacce274f/bom/pom.xml#L112

Question:
* Is there any reason for this exclusion?
* Do you plan to release it soon?
* If not, why is it referenced in your own bom pom then?
* Do you suggest to use the previous version `2.17.2` instead?

Kind regards
Alexander

**Comment by liga-oz** [comment]
Hi @newtork,

the spring boot modules are not released any longer as the Spring Boot 2 is out of maintenance. You have to use the latest available which is 2.17.2

 https://github.com/SAP/cloud-security-services-integration-library/tree/main-2.x?tab=readme-ov-file#warning-announcement-of-end-of-support-for-our-spring-libraries

Cheers,
Liga

**Comment by MatKuhr** [comment]
Hi Liga, in that case I think you probably need to remove it from your BOM? or hard-code the version in the BOM to 2.17.2?

Otherwise the BOM is breaking user's projects, because your BOM is forcing them onto a version that doesn't exist and users have to override the version coming from the BOM.

**Comment by liga-oz** [comment]
@MatKuhr right, good point, thanks for a pointer I'l fix that ✋🏻

**Comment by MatKuhr** [comment]
@liga-oz sounds great, thanks! Could you please ping us here or via mail once a release with the fixed BOM will be available?  Then we can time the upgrade for Cloud SDK 4.X to increase the version from 2.17.2 to 2.12.4 (or whatever the new version will be 😉 ).

**Comment by finkmanAtSap** [comment]
Hi Matthias, Liga is out of office this week but I think Monday next week, there will be a new release 🤞🏻

**Comment by MatKuhr** [comment]
Cool! Do you already know if the BOM will be fixed with that release?

**Comment by liga-oz** [comment]
the fix is available in 2.17.4
