### ISSUE TITLE
FileNotFoundException - HybridIdentityServicesProofTokenAutoConfiguration class

### ISSUE THREAD

**Issue by SanjayM13** [SAP/cloud-security-services-integration-library#1634]
Hello Colleagues,

We are using latest version of spring-security which is 3.5.3.

During build, the tests are erroring out with IllegalStateException : Failed to load application context which was caused by

java.lang.IllegalStateException: Unable to read meta-data for class com.sap.cloud.security.spring.autoconfig.HybridIdentityServicesProofTokenAutoConfiguration
Caused by: java.io.FileNotFoundException: class path resource [com/sap/cloud/security/spring/autoconfig/HybridIdentityServicesProofTokenAutoConfiguration.class] cannot be opened because it does not exist

Can you please help us out here?

Regards,
Sanjay

**Comment by finkmanAtSap** [comment]
https://github.com/SAP/cloud-security-services-integration-library?tab=readme-ov-file#how-to-get-support
