### ISSUE TITLE
Need information on replaces libraries from security.xsuaa to security.spring

### ISSUE THREAD

**Issue by 95nsp2017** [SAP/cloud-security-services-integration-library#1635]
Hi Colleagues, 

We are in the process of upgrading CAP version from `2.4.1` to `3.2.0`.

In this process, we are removing all the usages of the `com.sap.cloud.security.xsuaa` as we understood that this is now getting deprecated and we need to replace them with the available `com.sap.cloud.security.spring` libraries.
For the same we are following this [migration guide](https://github.com/SAP/cloud-security-services-integration-library/blob/367e42167e65a54eb81b0ef3fefd158620518528/spring-security/Migration_SpringXsuaaProjects.md).

However in this regards, we want to understand if we should be removing all the `com.sap.cloud.security.xsuaa` related libraries such as `com.sap.cloud.security.xsuaa.client` and `com.sap.cloud.security.xsuaa.tokenflows`, particularly the ones shown in the image below.
![image](https://github.com/user-attachments/assets/d1aad2f4-f0fd-4368-b376-6fa7ac060946)

If yes, can you please guide us how shall we replace these libraries as from the migration guide, it is difficult to find the replacement for these libraries.

This is a major blocker for us in the CAP upgrade process, hence can you please help us with this issue. 

Please let us know if any further information is required.

The main repo of our project is given below:
For Resource Management umbrella module : https://github.tools.sap/Cloud4RM/Resource-Management

**Comment by finkmanAtSap** [comment]
https://github.com/SAP/cloud-security-services-integration-library?tab=readme-ov-file#how-to-get-support
