### ISSUE TITLE
Deprecate AbstractTokenAuthenticator.extractFromHeader 

### ISSUE THREAD

**Issue by nenaraab** [SAP/cloud-security-services-integration-library#487]
https://github.com/SAP/cloud-security-xsuaa-integration/blob/f26295561c438c8de552e32fd8b92d89556635dc/java-security/src/main/java/com/sap/cloud/security/servlet/AbstractTokenAuthenticator.java#L137

Might be replaced with HybridTokenFactory.

**Comment by finkmanAtSap** [comment]
Closing this as Github Issue section is no longer maintained.
